name: Workflow13

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  trigger-emr:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo (REQUIRED)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials (MUST come before AWS CLI)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Upload Spark scripts to S3
      - name: Upload Spark scripts to S3
        run: |
          aws s3 cp src/ s3://${{ secrets.S3_BUCKET }}/scripts/ --recursive


      - name: Trigger EMR Spark jobs (WRITE → READ)
        run: |
          aws emr add-steps \
            --cluster-id "${{ secrets.EMR_CLUSTER_ID }}" \
            --steps \
            Type=Spark,Name=CorporateRegistryIcebergMerge,ActionOnFailure=CONTINUE,Args=[--deploy-mode,cluster,s3://${{ secrets.S3_BUCKET }}/scripts/single_pipliene.py]